services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        # Wartość trafi do buildu jako VITE_API_BASE_URL
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "4173:4173"